Inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),

    # auth
    path('signup/', permission_required('main.add_user')
         (views.SignUpView.as_view()), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path("logout/", login_required(auth_views.LogoutView.as_view()), name="logout"),

    # store urls
    path('store/index', permission_required('main.view_store')
         (views.Index.as_view()), name='store_index'),
    path('store/create/', permission_required('main.add_store')
         (views.StoreCreateView.as_view()), name='create_store'),
    path('store/update/<int:pk>',
         permission_required('main.change_store')(views.StoreUpdateView.as_view()), name='update_store'),
    path('store/read/<int:pk>', permission_required('main.view_store')
         (views.StoreReadView.as_view()), name='read_store'),
    path('store/delete/<int:pk>',
         permission_required('main.delete_store')(views.StoreDeleteView.as_view()), name='delete_store'),
    path('stores/', views.stores, name='stores'),

    # oulet urls
    path('outlet/index', permission_required('main.view_outlet')
         (views.OutletIndex.as_view()), name='outlet_index'),
    path('outlet/create/', permission_required('main.add_outlet')
         (views.OutletCreateView.as_view()), name='create_outlet'),
    path('outlet/update/<int:pk>',
         permission_required('main.change_outlet')(views.OutletUpdateView.as_view()), name='update_outlet'),
    path('outlet/read/<int:pk>', permission_required('main.view_outlet')
         (views.OutletReadView.as_view()), name='read_outlet'),
    path('outlet/delete/<int:pk>',
         permission_required('main.delete_outlet')(views.OutletDeleteView.as_view()), name='delete_outlet'),
    path('outlets/', views.outlets, name='outlets'),

    # users urls
    path('user/index', permission_required('main.view_user')
         (views.UserIndex.as_view()), name='user_index'),
    path('user/update/<int:pk>',
         permission_required('main.change_user')(views.UserUpdateView.as_view()), name='update_user'),
    path('user/read/<int:pk>', permission_required('main.view_user')
         (views.UserReadView.as_view()), name='read_user'),
    path('user/delete/<int:pk>',
         permission_required('main.delete_user')(views.UserDeleteView.as_view()), name='delete_user'),
    path('user/', views.users, name='users'),

    # item urls
    path('item/index', permission_required('main.view_item')
         (views.ItemIndex.as_view()), name='item_index'),
    path('item/create/', permission_required('main.add_item')
         (views.ItemCreateView.as_view()), name='create_item'),
    path('item/update/<int:pk>',
         permission_required('main.change_item')(views.ItemUpdateView.as_view()), name='update_item'),
    path('item/read/<int:pk>', permission_required('main.view_item')
         (views.ItemReadView.as_view()), name='read_item'),
    path('item/delete/<int:pk>',
         permission_required('main.delete_item')(views.ItemDeleteView.as_view()), name='delete_item'),
    path('items/', views.items, name='items'),

    # supplier urls
    path('supplier/index', permission_required('main.view_supplier')
         (views.SupplierIndex.as_view()), name='supplier_index'),
    path('supplier/create/', permission_required('main.add_supplier')(views.SupplierCreateView.as_view()),
         name='create_supplier'),
    path('supplier/update/<int:pk>',
         permission_required('main.change_supplier')(views.SupplierUpdateView.as_view()), name='update_supplier'),
    path('supplier/read/<int:pk>',
         permission_required('main.view_supplier')(views.SupplierReadView.as_view()), name='read_supplier'),
    path('supplier/delete/<int:pk>',
         permission_required('main.delete_supplier')(views.SupplierDeleteView.as_view()), name='delete_supplier'),
    path('suppliers/', views.suppliers, name='suppliers'),

    # ops
    path('purchase/', views.purchase, name='purchase'),
    path('dispatch/', views.dispatch, name='dispatch'),
    path('analysis', views.chart, name='analysis'),

    # chart
    path('plot/', views.plot, name='plot'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from main.choices import groups, purchase, dispatch, gender_choices
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, UserManager
from django.utils.translation import ugettext as _
from django.utils import timezone


class Outlet(models.Model):  #
    date_modified = models.DateTimeField(_('Date and Time Modified'), null=False, blank=False, unique=False,
                                         auto_now=True)
    date_added = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)

    address = models.CharField(
        _("Address"), max_length=500, null=True, blank=True)

    name = models.CharField(_('Name'), max_length=30, null=False, blank=False,
                            unique=True)
    description = models.CharField(_('Description'), max_length=100, null=False, blank=False,
                                   unique=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return '/outlet/%s' % self.title

    class Meta:
        ordering = ['-date_modified']
        verbose_name = _('Outlet')
        verbose_name_plural = _('Outlets')


class Till(models.Model):  #
    date_added = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)

    till_number = models.CharField(
        _("Till Number"), max_length=500, null=True, blank=True)

    outlet = models.ForeignKey(
        Outlet, blank=False, null=True, unique=False, on_delete=models.CASCADE)

    description = models.CharField(_('Description'), max_length=100, null=False, blank=False,
                                   unique=True)

    def get_absolute_url(self):
        return '/till/%s' % self.title

    class Meta:
        ordering = ['-till_number']
        verbose_name = _('Till')
        verbose_name_plural = _('Tills')


class Store(models.Model):  #
    date_modified = models.DateTimeField(_('Date and Time Modified'), null=False, blank=False, unique=False,
                                         auto_now=True)
    date_added = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)

    address = models.CharField(
        _("Address"), max_length=500, null=True, blank=True)

    name = models.CharField(_('Name'), max_length=30, null=False, blank=False,
                            unique=True)
    description = models.CharField(_('Description'), max_length=100, null=False, blank=False,
                                   unique=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return '/store/%s' % self.title

    class Meta:
        ordering = ['-date_modified']
        verbose_name = _('Store')
        verbose_name_plural = _('Stores')


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """creates and saves a new user"""
        if not email:
            raise ValueError("Users must have an email address")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Create a super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class Supplier(models.Model):
    email = models.EmailField(_("email address"), max_length=255, unique=True)
    name = models.CharField(_("Name"), max_length=255, null=True)
    address = models.CharField(_("Address"), max_length=255)

    def __str__(self):
        return str(self.name)


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports using email instead of username"""
    email = models.EmailField(_("email address"), max_length=255, unique=True)
    first_name = models.CharField(_("first name"), max_length=255, null=True)
    last_name = models.CharField(_("last name"), max_length=255)
    gender = models.CharField(
        _("gender"), max_length=1, choices=gender_choices)
    store = models.ForeignKey(
        Store, blank=False, null=True, unique=False, on_delete=models.CASCADE)
    date_joined = models.DateTimeField(_("Date joined"), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Item(models.Model):  #
    date_modified = models.DateTimeField(_('Date and Time Modified'), null=False, blank=False, unique=False,
                                         auto_now=True)
    date_added = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)

    quantity = models.IntegerField(
        _('Quantity'), default=10, null=False, blank=False)
    re_order_level = models.IntegerField(
        _('Re-order Level'), default=5, null=False, blank=False)
    id = models.AutoField(null=False, blank=False, primary_key=True)

    title = models.CharField(_('Title'), max_length=30, null=False, blank=False,
                             unique=True)
    barcode = models.CharField(_('Barcode'), max_length=12, null=False, blank=False,
                               unique=True)
    description = models.CharField(_('Description'), max_length=100, null=False, blank=False,
                                   unique=False)
    supplier = models.ForeignKey(
        Supplier, blank=True, null=True, unique=False, on_delete=models.CASCADE)
    unit_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)

    def get_absolute_url(self):
        return '/items/%s' % self.title

    class Meta:
        ordering = ['-date_modified']
        verbose_name = _('Item')
        verbose_name_plural = _('Items')


class Dispatch(models.Model):
    date = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)
    store = models.ForeignKey(
        Store, blank=False, null=True, unique=False, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, blank=False, null=True, unique=False, on_delete=models.CASCADE)
    item = models.ForeignKey(
        Item, blank=False, null=True, unique=False, on_delete=models.CASCADE)

    initial_quatity = models.IntegerField(
        _('Initial Quantity'), default=10, null=False, blank=False)

    quantity = models.IntegerField(
        _('Quantity'), default=10, null=False, blank=False)

    new_quatity = models.IntegerField(
        _('New Quantity'), default=10, null=False, blank=False)

    id = models.AutoField(null=False, blank=False, primary_key=True)
    transaction_type = models.CharField(
        _('Transaction Type'), default='add', max_length=30, unique=False, choices=dispatch)
    money_value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-date']
        verbose_name = _('Purchase')
        verbose_name_plural = _('Purchases')


class Purchase(models.Model):
    date = models.DateTimeField(
        _('Date and Time'), null=False, blank=False, unique=False, auto_now_add=True)
    store = models.ForeignKey(
        Store, blank=False, null=True, unique=False, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, blank=False, null=True, unique=False, on_delete=models.CASCADE)
    item = models.ForeignKey(
        Item, blank=False, null=True, unique=False, on_delete=models.CASCADE)

    initial_quatity = models.IntegerField(
        _('Initial Quantity'), default=10, null=False, blank=False)

    quantity = models.IntegerField(
        _('Quantity'), default=10, null=False, blank=False)

    new_quatity = models.IntegerField(
        _('New Quantity'), default=10, null=False, blank=False)

    id = models.AutoField(null=False, blank=False, primary_key=True)
    transaction_type = models.CharField(
        _('Transaction Type'), default='add', max_length=30, unique=False, choices=purchase)
    money_value = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return str(self.id)

    class Meta:
        ordering = ['-date']
        verbose_name = _('Purchase')
        verbose_name_plural = _('Purchases')


class Recipt(models.Model):
    ref_number = models.CharField(
        max_length=6, null=False, blank=False, unique=True, primary_key=True)
    date_of_generated = models.DateTimeField(
        _('Date and Time '), null=False, blank=False, unique=False, auto_now_add=True)
    transaction = models.ForeignKey(
        Purchase, blank=False, null=True, unique=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.refNumber

    class Meta:
        ordering = ['date_of_generated']


class Invoice(models.Model):
    ref_number = models.CharField(
        max_length=5, null=False, blank=False, unique=True, primary_key=True)
    date_of_generated = models.DateTimeField(
        _('Date and Time '), null=False, blank=False, unique=False, auto_now_add=True)
    transaction = models.ForeignKey(
        Dispatch, blank=False, null=True, unique=False, on_delete=models.CASCADE)

    def __str__(self):
        return self.refNumber

    class Meta:
        ordering = ['date_of_generated']


class SuppliedBy(models.Model):
    date_modified = models.DateTimeField(
        _("Date and Time"), null=False, blank=False, unique=False, auto_now=True)
    date_added = models.DateTimeField(
        _("Date and Time"), null=False, blank=False, unique=False, auto_now_add=True)
    id = models.AutoField(null=False, blank=False, primary_key=True)
    store = models.ForeignKey(

templates/_items_table.html
<div class="table-mi">
  <table id="books-table" class="table table-shopping">
    <thead>
      <tr>
        <th class="text-center">#</th>
        <th>Barcode</th>
        <th>Title</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Re-Order Level</th>
        <th>Supplier</th>
        <th>Date Added</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <td class="text-center">{{item.id}}</td>
        <td>{{item.barcode}}</td>
        <td>{{item.title}}</td>
        <td>{{item.description}}</td>
        {% if item.quantity <= item.re_order_level %} 
        <td class="font-weight-bold text-danger">
          {{item.quantity}}
          </td>
          {% else %}
          <td>{{item.quantity}}</td>
          {% endif %}
          <td>R {{item.unit_price}}</td>
          <td>{{item.re_order_level}}</td>
          <td>{{item.supplier}}</td>
          <td>{{item.date_added}}</td>
          <td>
            <!-- Read item buttons -->
            <button type="button" class="bs-modal read-book btn btn-sm btn-success"
              data-form-url="{% url 'read_item' item.id %}">
              <span class="fa fa-eye"></span>
            </button>
            {% if perms.main.change_item %}
            <!-- Update item buttons -->
            <button type="button" class="update-book btn btn-sm btn-info-mi"
              data-form-url="{% url 'update_item' item.id %}">
              <span class="fa fa-pencil"></span>
            </button>
            {% endif %}
            {% if perms.main.delete_item %}
            <!-- Delete item buttons -->
            <button type="button" class="bs-modal delete-book btn btn-sm btn-danger"
              data-form-url="{% url 'delete_item' item.id %}">
              <span class="fa fa-trash"></span>
            </button>
            {% endif %}
          </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

templates/_modal.html
<div class="modal fade bd-example-modal-lg " id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog  modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade bd-example-modal-l" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog  modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>

templates/chart.html
{% extends 'modal_base.html' %}
{% load static %}

{% block content %}

{% include "_modal.html" %}
<nav class="navbar navbar-expand-lg bg-info-mi">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}"> <b class="nav-ta">Dashboard</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'item_index' %}"> <b class="nav-ta">Items</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store_index' %}"><b class="nav-ta">Store Rooms</b></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'outlet_index' %}"> <b class="nav-ta">Outlets</b></a>
        </li>
        {% if perms.main.view_supplier %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'supplier_index' %}"><b class="nav-ta">Suppliers</b></a>
        </li>
        {% endif %}
        {% if perms.main.view_dispatch %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'analysis' %}"> <b class="nav-ta">Reports</b></a>
        </li>
        {% endif %}
        {% if perms.main.view_user %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user_index' %}"><b class="nav-ta">Users</b></a>
        </li>
        {% endif %}
      </ul>
    </div>
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="javascript:;" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <strong class="nav-ta"><span data-toggle="tooltip" title="{{user}} logged in"><i
                class="material-icons">face</i></span></strong>
        </a>
        <div class="dropdown-menu bg-info-mi" aria-labelledby="navbarDropdownMenuLink">
          <a class="btn btn-info-mi" href="{% url 'logout' %}" style="width:100%;"><b class="nav-ta">Logout</b></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="container">
  <div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
      <canvas id="myChart" width="40" height="40">

      </canvas>
      <canvas id="bar-chart-grouped" width="2500" height="2000"></canvas>

    </div>
    <div class="table-responsive">
      <h3 class="text-center">Reports</h3>
      <div class="form-row text-center">
      </div>


      <div class="col-12 mb-3">
        <div class="row mt-1">
          <div class="col-md-3">
          </div>
          <div class="col-md-8">
            <form method="post" action="{% url 'analysis' %}">
              {% csrf_token %}
              <div class="form-check form-check-inline">
                <label>Duration </label>
                <div class="mr-3"></div>
                <select name='period' class="form-control form-select-lg mr-3" aria-label=".form-select-sm example">
                  <option value="1" selected>Last 24 Hrs</option>
                  <option value="7">Last 7 Days</option>
                  <option value="30">Last Month</option>
                  <option value="365">Last Year</option>
                </select>
                <div class="mr-3"></div>
                <label>Transaction Type </label>
                <div class="mr-3"></div>
                <select name='type' class="form-control form-select-lg mr-3 " aria-label=".form-select-sm example">
                  <option value="all" selected>All</option>
                  <option value="dispatch">Dispatch</option>
                  <option value="purchase">Purchase</option>
                </select>
                <div class="mr-3"></div>
                <button class="btn btn-info-mi btn-round">
                  <i class="material-icons">filter_list</i> Filter
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="table-mi mt-5">
          <table id="books-table" class="table table-shopping">
            <thead>
              <tr>
                <th>Date Of Transaction</th>
                <th>Store</th>
                <th>Proccessed By </th>
                <th>Item</th>
                <th>Initial Quantity</th>
                <th>Transaction Quantity</th>
                <th>New Quantity</th>
                <th>Transaction Value</th>
                <th>Transaction Type</th>
              </tr>
            </thead>
            <tbody>
              {% for transaction in transactions %}
              <tr>
                <td>{{transaction.date}}</td>
                <td>{{transaction.store}}</td>
                <td>{{transaction.user}}</td>
                <td>{{transaction.item.title}}</td>
                <td>{{transaction.initial_quatity}}</td>
                <td>{{transaction.quantity}}</td>
                <td>{{transaction.new_quatity}}</td>
                <td>R {{transaction.money_value}}</td>
                <td>{{transaction.transaction_type}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


{% block extrascripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
<script>
  var endpoint = "{% url 'plot'  %}"
  $.ajax
    ({
      type: "GET",
      url: endpoint,
      success: function (data) {
        var labels = []
        var quantity = []
        var re_order_level = []
        var ctx = document.getElementById('myChart').getContext('2d');

        data.map(data => {
          labels.push(data.title)
        })
        data.map(data => {
          quantity.push(data.quantity)
        })
        data.map(data => {
          re_order_level.push(data.re_order_level)
        })
        new Chart(document.getElementById("bar-chart-grouped"), {
          type: 'bar',
          data: {
            labels: labels,
            datasets: [
              {
                label: "Available Quantity",
                backgroundColor: "#8e5ea2",
                data: quantity
              },
              {
                label: "Re-Order Level",
                backgroundColor: "#3e95cd",
                data: re_order_level
              }
            ]
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: true
                }
              }]
            },
            title: {
              display: true,
              text: 'Stock Quantity vs Re-Order Level '
            }
          }
        });
      },
      error: function (data) {
        console.log(data)
      }
    });


</script>
{% endblock extrascripts %}


{% endblock %}

templates/dashboard.html
{% extends 'modal_base.html' %}
{% load static %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-info-mi">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard' %}"> <b class="nav-ta">Dashboard</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'item_index' %}"> <b class="nav-ta">Items</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'store_index' %}"><b class="nav-ta">Store Rooms</b></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'outlet_index' %}"> <b class="nav-ta">Outlets</b></a>
                </li>
                {% if perms.main.view_supplier %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'supplier_index' %}"><b class="nav-ta">Suppliers</b></a>
                </li>
                {% endif %}
                {% if perms.main.view_dispatch %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'analysis' %}"> <b class="nav-ta">Reports</b></a>
                </li>
                {% endif %}
                {% if perms.main.view_user %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_index' %}"><b class="nav-ta">Users</b></a>
                </li>
                {% endif %}
            </ul>
        </div>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="javascript:;" id="navbarDropdownMenuLink"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <strong class="nav-ta"><span data-toggle="tooltip" title="{{user}} logged in"><i
                                class="material-icons">face</i></span></strong>
                </a>
                <div class="dropdown-menu bg-info-mi" aria-labelledby="navbarDropdownMenuLink">
                    <a class="btn btn-info-mi" href="{% url 'logout' %}" style="width:100%;"><b class="nav-ta">Logout</b></a>
                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="dashboard-mi">
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-4 ">
            <a class="a-mi" href="{% url 'item_index' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Items</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        To get information about your Inventory
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a class="a-mi" href="{% url 'outlet_index' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Outlets</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        To get information about your Outlets click
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        {% if perms.main.view_dispatch %}
        <div class="col-md-4">
            <a class="a-mi" href="{% url 'analysis' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Reports</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        Reports and graphical analysis
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
        {% if perms.main.view_user %}
        <div class="col-md-4">
            <a class="a-mi" href="{% url 'user_index' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Users</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        To get information about your Users click

                    </div>
                </div>
            </a>
        </div>
        {% endif %}

        <div class="col-md-2">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-4 ">
            <a class="a-mi" href="{% url 'purchase' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Purchase</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        Restocking
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4">
            <a class="a-mi" href="{% url 'dispatch' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Dispatch</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        Checking out
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2">
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-4 ">
            <a class="a-mi" href="{% url 'supplier_index' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Supplier</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        Restocking and checking out
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-4 ">
            <a class="a-mi" href="{% url 'store_index' %}">
                <div class="card">
                    <div class="card-header card-header-info">
                        <h4 class="card-title"><b class="nav-ta">Store Rooms</b></h4>
                        <p class="category"></p>
                    </div>
                    <div class="card-body">
                        To get information about your Store Rooms click
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-2">
        </div>
    </div>
</div>
{% endblock %}